#pragma once

#include <stdint.h>

#if __has_include("secrets.h")
#include "secrets.h"
#endif

// Build modes selected by platformio.ini.
#define APP_MODE_FULL_PROTOTYPE 0
#define APP_MODE_TEST_DHT11 1
#define APP_MODE_TEST_GPS 2
#define APP_MODE_TEST_I2C_SCANNER 3
#define APP_MODE_TEST_ADXL345 4
#define APP_MODE_TEST_L3G4200D 5
#define APP_MODE_TEST_HMC5883L 6
#define APP_MODE_TEST_BMP180 7
#define APP_MODE_TEST_GY801 8
#define APP_MODE_TEST_WIFI 9
#define APP_MODE_TEST_MQTT_WIFI 10
#define APP_MODE_CALIBRATE_BMP180 11
#define APP_MODE_TEST_BH1750 12
#define APP_MODE_TEST_MICROSD 13
#define APP_MODE_TEST_SIM800L_AT 14
#define APP_MODE_TEST_SIM800L_GPRS 15
#define APP_MODE_TEST_SIM800L_MQTT 16
#define APP_MODE_TEST_SIM800L_MQTT_TLS 17
#define APP_MODE_TEST_LOCAL_WEB 18
#define APP_MODE_TEST_LOCAL_OTA 19
#define APP_MODE_FULL_PROTOTYPE_CELLULAR 20
#define APP_MODE_VEHICLESENSE_WIFI 21

#ifndef APP_MODE
#define APP_MODE APP_MODE_FULL_PROTOTYPE
#endif

#ifndef DEVICE_ID
// Kept unchanged for backward compatibility with deployed schema-v2 devices.
#define DEVICE_ID "bus_iot_prototype_01"
#endif

#ifndef VEHICLE_ID
#define VEHICLE_ID "vehicle_prototype_01"
#endif

#ifndef FIRMWARE_VERSION
#define FIRMWARE_VERSION "0.2.0"
#endif

#ifndef SERIAL_BAUD
#define SERIAL_BAUD 115200
#endif

#define LOG_LEVEL_DEBUG 0
#define LOG_LEVEL_INFO 1
#define LOG_LEVEL_WARN 2
#define LOG_LEVEL_ERROR 3
#define LOG_LEVEL_NONE 4

#ifndef LOG_LEVEL
#define LOG_LEVEL LOG_LEVEL_INFO
#endif

#ifndef GPS_BAUD
#define GPS_BAUD 9600
#endif

#ifndef DHT_READ_INTERVAL_MS
#define DHT_READ_INTERVAL_MS 2000UL
#endif

#ifndef BARO_READ_INTERVAL_MS
#define BARO_READ_INTERVAL_MS 2000UL
#endif

#ifndef LIGHT_READ_INTERVAL_MS
#define LIGHT_READ_INTERVAL_MS 1000UL
#endif

#ifndef IMU_READ_INTERVAL_MS
#define IMU_READ_INTERVAL_MS 100UL
#endif

#ifndef TELEMETRY_INTERVAL_MS
#define TELEMETRY_INTERVAL_MS 10000UL
#endif

#ifndef NTP_SYNC_RETRY_INTERVAL_MS
#define NTP_SYNC_RETRY_INTERVAL_MS 60000UL
#endif

#ifndef NTP_SERVER_PRIMARY
#define NTP_SERVER_PRIMARY "pool.ntp.org"
#endif

#ifndef NTP_SERVER_SECONDARY
#define NTP_SERVER_SECONDARY "time.cloudflare.com"
#endif

#ifndef TEST_OUTPUT_INTERVAL_MS
#define TEST_OUTPUT_INTERVAL_MS 2000UL
#endif

#ifndef I2C_SCAN_INTERVAL_MS
#define I2C_SCAN_INTERVAL_MS 10000UL
#endif

#ifndef SENSOR_RETRY_INTERVAL_MS
#define SENSOR_RETRY_INTERVAL_MS 30000UL
#endif

#ifndef SD_RETRY_INTERVAL_MS
#define SD_RETRY_INTERVAL_MS 30000UL
#endif

#ifndef SIM800_ACTION_INTERVAL_MS
#define SIM800_ACTION_INTERVAL_MS 5000UL
#endif

#ifndef SIM800_STATUS_INTERVAL_MS
#define SIM800_STATUS_INTERVAL_MS 30000UL
#endif

#ifndef SIM800_TCP_TEST_INTERVAL_MS
#define SIM800_TCP_TEST_INTERVAL_MS 30000UL
#endif

#ifndef LOCAL_WEB_SNAPSHOT_INTERVAL_MS
#define LOCAL_WEB_SNAPSHOT_INTERVAL_MS 1000UL
#endif

#ifndef GPS_FIX_MAX_AGE_MS
#define GPS_FIX_MAX_AGE_MS 5000UL
#endif

#ifndef GPS_NO_DATA_WARNING_MS
#define GPS_NO_DATA_WARNING_MS 5000UL
#endif

#ifndef WIFI_CONNECT_TIMEOUT_MS
#define WIFI_CONNECT_TIMEOUT_MS 12000UL
#endif

#ifndef RECONNECT_BACKOFF_MIN_MS
#define RECONNECT_BACKOFF_MIN_MS 5000UL
#endif

#ifndef RECONNECT_BACKOFF_MAX_MS
#define RECONNECT_BACKOFF_MAX_MS 30000UL
#endif

#ifndef I2C_TIMEOUT_MS
#define I2C_TIMEOUT_MS 50U
#endif

#ifndef MQTT_BUFFER_SIZE
#define MQTT_BUFFER_SIZE 2304U
#endif

#ifndef MQTT_KEEPALIVE_SECONDS
#define MQTT_KEEPALIVE_SECONDS 30U
#endif

#ifndef MQTT_SOCKET_TIMEOUT_SECONDS
#define MQTT_SOCKET_TIMEOUT_SECONDS 3U
#endif

#ifndef VEHICLESENSE_MQTT_BUFFER_SIZE
#define VEHICLESENSE_MQTT_BUFFER_SIZE 4096U
#endif

#ifndef VEHICLESENSE_MQTT_TASK_STACK_SIZE
#define VEHICLESENSE_MQTT_TASK_STACK_SIZE 8192U
#endif

#ifndef MQTT_COMMAND_BUFFER_SIZE
#define MQTT_COMMAND_BUFFER_SIZE 1024U
#endif

#ifndef TELEMETRY_PAYLOAD_BUFFER_SIZE
#define TELEMETRY_PAYLOAD_BUFFER_SIZE 2048U
#endif

#ifndef LOCAL_WEB_JSON_BUFFER_SIZE
#define LOCAL_WEB_JSON_BUFFER_SIZE 1536U
#endif

#ifndef SIM800_BAUD
#define SIM800_BAUD 9600UL
#endif

#ifndef SD_SPI_FREQUENCY_HZ
#define SD_SPI_FREQUENCY_HZ 10000000UL
#endif

#ifndef SD_LOG_ROTATE_BYTES
#define SD_LOG_ROTATE_BYTES 1048576UL
#endif

#ifndef OFFLINE_QUEUE_MAX_RECORDS
#define OFFLINE_QUEUE_MAX_RECORDS 256U
#endif

#ifndef OFFLINE_QUEUE_MAX_BYTES
#define OFFLINE_QUEUE_MAX_BYTES 786432UL
#endif

#ifndef OFFLINE_QUEUE_MAX_AGE_SECONDS
#define OFFLINE_QUEUE_MAX_AGE_SECONDS 604800UL
#endif

#ifndef OFFLINE_QUEUE_REPLAY_INTERVAL_MS
#define OFFLINE_QUEUE_REPLAY_INTERVAL_MS 250UL
#endif

#ifndef MQTT_PUBACK_TIMEOUT_MS
#define MQTT_PUBACK_TIMEOUT_MS 30000UL
#endif

#ifndef BH1750_MAX_LUX
#define BH1750_MAX_LUX 120000.0F
#endif

#ifndef CELLULAR_MQTT_USE_TLS
#define CELLULAR_MQTT_USE_TLS 1
#endif

#ifndef ALLOW_INSECURE_CELLULAR_MQTT
#define ALLOW_INSECURE_CELLULAR_MQTT 0
#endif

#ifndef BARO_DEFAULT_SEA_LEVEL_PRESSURE_HPA
#define BARO_DEFAULT_SEA_LEVEL_PRESSURE_HPA 1008.00F
#endif

// Keep this offset at zero until the BMP180 is compared with a calibrated
// barometer at the same location and height.
#ifndef BARO_PRESSURE_OFFSET_HPA
#define BARO_PRESSURE_OFFSET_HPA 0.00F
#endif

#ifndef BARO_CALIBRATION_KNOWN_ALTITUDE_M
#define BARO_CALIBRATION_KNOWN_ALTITUDE_M 85.00F
#endif

#ifndef BARO_CALIBRATION_DURATION_MS
#define BARO_CALIBRATION_DURATION_MS 60000UL
#endif

#ifndef BARO_CALIBRATION_MIN_SAMPLES
#define BARO_CALIBRATION_MIN_SAMPLES 30U
#endif

#ifndef BARO_CALIBRATION_MIN_SATELLITES
#define BARO_CALIBRATION_MIN_SATELLITES 6U
#endif

#ifndef BARO_CALIBRATION_MAX_HDOP
#define BARO_CALIBRATION_MAX_HDOP 2.5F
#endif

#ifndef BARO_CALIBRATION_MAX_SPEED_KMH
#define BARO_CALIBRATION_MAX_SPEED_KMH 1.0F
#endif

#ifndef BARO_CALIBRATION_MAX_ALTITUDE_SPREAD_M
#define BARO_CALIBRATION_MAX_ALTITUDE_SPREAD_M 10.0F
#endif

// ADXL345 six-position calibration in m/s^2.
// Raw readings are corrected as: calibrated = (raw - offset) * scale.
#ifndef ADXL_OFFSET_X
#define ADXL_OFFSET_X -0.3607F
#endif

#ifndef ADXL_OFFSET_Y
#define ADXL_OFFSET_Y -0.1363F
#endif

#ifndef ADXL_OFFSET_Z
#define ADXL_OFFSET_Z 1.2093F
#endif

#ifndef ADXL_SCALE_X
#define ADXL_SCALE_X 0.95937F
#endif

#ifndef ADXL_SCALE_Y
#define ADXL_SCALE_Y 0.96348F
#endif

#ifndef ADXL_SCALE_Z
#define ADXL_SCALE_Z 0.99721F
#endif

// Expected 7-bit addresses. Alternate addresses are probed where supported.
#define ADXL345_ADDRESS_PRIMARY 0x53
#define ADXL345_ADDRESS_ALTERNATE 0x1D
#define L3G4200D_ADDRESS_PRIMARY 0x69
#define L3G4200D_ADDRESS_ALTERNATE 0x68
#define HMC5883L_ADDRESS 0x1E
#define QMC5883L_POSSIBLE_ADDRESS 0x0D
#define BMP180_ADDRESS 0x77
#define BH1750_ADDRESS_PRIMARY 0x23
#define BH1750_ADDRESS_ALTERNATE 0x5C

// Safe defaults allow sensor-only environments to compile without secrets.h.
#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif

#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD ""
#endif

#ifndef MQTT_HOST
#define MQTT_HOST ""
#endif

#ifndef MQTT_PORT
#define MQTT_PORT 1883
#endif

#ifndef MQTT_USERNAME
#define MQTT_USERNAME ""
#endif

#ifndef MQTT_PASSWORD
#define MQTT_PASSWORD ""
#endif

#ifndef MQTT_TOPIC
#define MQTT_TOPIC "v1/devices/me/telemetry"
#endif

#ifndef HIVEMQ_HOST
#define HIVEMQ_HOST ""
#endif

#ifndef HIVEMQ_PORT
#define HIVEMQ_PORT 8883
#endif

#ifndef HIVEMQ_USERNAME
#define HIVEMQ_USERNAME ""
#endif

#ifndef HIVEMQ_PASSWORD
#define HIVEMQ_PASSWORD ""
#endif

#ifndef CELLULAR_APN
#define CELLULAR_APN ""
#endif

#ifndef CELLULAR_APN_USER
#define CELLULAR_APN_USER ""
#endif

#ifndef CELLULAR_APN_PASSWORD
#define CELLULAR_APN_PASSWORD ""
#endif

#ifndef CELLULAR_SIM_PIN
#define CELLULAR_SIM_PIN ""
#endif

#ifndef CELLULAR_MQTT_HOST
#define CELLULAR_MQTT_HOST ""
#endif

#ifndef CELLULAR_MQTT_PORT
#define CELLULAR_MQTT_PORT 8883
#endif

#ifndef CELLULAR_MQTT_USERNAME
#define CELLULAR_MQTT_USERNAME ""
#endif

#ifndef CELLULAR_MQTT_PASSWORD
#define CELLULAR_MQTT_PASSWORD ""
#endif

#ifndef CELLULAR_MQTT_TOPIC
#define CELLULAR_MQTT_TOPIC "buses/prototype/telemetry"
#endif

#ifndef MQTT_TEST_HOST
#define MQTT_TEST_HOST ""
#endif

#ifndef MQTT_TEST_PORT
#define MQTT_TEST_PORT 1883
#endif

#ifndef MQTT_TEST_USERNAME
#define MQTT_TEST_USERNAME ""
#endif

#ifndef MQTT_TEST_PASSWORD
#define MQTT_TEST_PASSWORD ""
#endif

#ifndef MQTT_TEST_TOPIC
#define MQTT_TEST_TOPIC "buses/prototype/diagnostics"
#endif

#ifndef LOCAL_AP_SSID
#define LOCAL_AP_SSID ""
#endif

#ifndef LOCAL_AP_PASSWORD
#define LOCAL_AP_PASSWORD ""
#endif

#ifndef LOCAL_ADMIN_USERNAME
#define LOCAL_ADMIN_USERNAME ""
#endif

#ifndef LOCAL_ADMIN_PASSWORD
#define LOCAL_ADMIN_PASSWORD ""
#endif
