"""initial VehicleSense schema

Revision ID: cd5ddc949e1d
Revises:
Create Date: 2026-07-20 20:16:43.427379
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cd5ddc949e1d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_failures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("topic", sa.String(length=512), nullable=False),
        sa.Column("payload_preview", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_failures")),
    )
    op.create_index(
        op.f("ix_ingestion_failures_received_at"),
        "ingestion_failures",
        ["received_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_failures_topic"), "ingestion_failures", ["topic"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("alert_thresholds", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicles")),
    )
    op.create_index(op.f("ix_vehicles_active"), "vehicles", ["active"], unique=False)
    op.create_index(op.f("ix_vehicles_vehicle_id"), "vehicles", ["vehicle_id"], unique=True)
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("firmware_version", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("status_reason", sa.String(length=120), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_status_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_boot_id", sa.BigInteger(), nullable=True),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("motion_candidate_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_candidate_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("gps_invalid_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("microphone_invalid_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_devices_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
    )
    op.create_index(op.f("ix_devices_device_id"), "devices", ["device_id"], unique=True)
    op.create_index(op.f("ix_devices_last_seen_at"), "devices", ["last_seen_at"], unique=False)
    op.create_index(op.f("ix_devices_simulated"), "devices", ["simulated"], unique=False)
    op.create_index(op.f("ix_devices_status"), "devices", ["status"], unique=False)
    op.create_index(op.f("ix_devices_vehicle_id"), "devices", ["vehicle_id"], unique=False)
    op.create_table(
        "acoustic_measurements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sample_id", sa.String(length=170), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("microphone_valid", sa.Boolean(), nullable=False),
        sa.Column("analysis_valid", sa.Boolean(), nullable=False),
        sa.Column("relative_level_dbfs", sa.Float(), nullable=True),
        sa.Column("peak_dbfs", sa.Float(), nullable=True),
        sa.Column("clipping", sa.Boolean(), nullable=True),
        sa.Column("category", sa.String(length=24), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("classifier_version", sa.String(length=40), nullable=True),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_acoustic_measurements_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_acoustic_measurements_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acoustic_measurements")),
        sa.UniqueConstraint("sample_id", name=op.f("uq_acoustic_measurements_sample_id")),
    )
    op.create_index(
        op.f("ix_acoustic_measurements_device_id"),
        "acoustic_measurements",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_acoustic_measurements_vehicle_id"),
        "acoustic_measurements",
        ["vehicle_id"],
        unique=False,
    )
    op.create_index(
        "ix_acoustic_vehicle_received",
        "acoustic_measurements",
        ["vehicle_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "commands",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("command_id", sa.String(length=100), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("command_type", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("acknowledgement", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_commands_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_commands_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commands")),
    )
    op.create_index(op.f("ix_commands_command_id"), "commands", ["command_id"], unique=True)
    op.create_index(op.f("ix_commands_device_id"), "commands", ["device_id"], unique=False)
    op.create_index(op.f("ix_commands_state"), "commands", ["state"], unique=False)
    op.create_table(
        "device_status_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=120), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_status_history_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_status_history")),
    )
    op.create_index(
        op.f("ix_device_status_history_device_id"),
        "device_status_history",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        "ix_status_device_changed",
        "device_status_history",
        ["device_id", "changed_at"],
        unique=False,
    )
    op.create_table(
        "telemetry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sample_id", sa.String(length=170), nullable=True),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("legacy", sa.Boolean(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("boot_id", sa.BigInteger(), nullable=True),
        sa.Column("sequence", sa.BigInteger(), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("uptime_ms", sa.BigInteger(), nullable=False),
        sa.Column("replayed", sa.Boolean(), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column("dht_valid", sa.Boolean(), nullable=False),
        sa.Column("gps_valid", sa.Boolean(), nullable=False),
        sa.Column("accel_valid", sa.Boolean(), nullable=False),
        sa.Column("gyro_valid", sa.Boolean(), nullable=False),
        sa.Column("mag_valid", sa.Boolean(), nullable=False),
        sa.Column("baro_valid", sa.Boolean(), nullable=False),
        sa.Column("imu_valid", sa.Boolean(), nullable=False),
        sa.Column("light_valid", sa.Boolean(), nullable=False),
        sa.Column("storage_valid", sa.Boolean(), nullable=False),
        sa.Column("microphone_valid", sa.Boolean(), nullable=False),
        sa.Column("acoustic_valid", sa.Boolean(), nullable=False),
        sa.Column("temperature_c", sa.Float(), nullable=True),
        sa.Column("humidity_percent", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("gps_altitude_m", sa.Float(), nullable=True),
        sa.Column("speed_kmh", sa.Float(), nullable=True),
        sa.Column("satellites", sa.Integer(), nullable=True),
        sa.Column("gps_hdop", sa.Float(), nullable=True),
        sa.Column("pressure_hpa", sa.Float(), nullable=True),
        sa.Column("baro_altitude_m", sa.Float(), nullable=True),
        sa.Column("light_lux", sa.Float(), nullable=True),
        sa.Column("accel_x", sa.Float(), nullable=True),
        sa.Column("accel_y", sa.Float(), nullable=True),
        sa.Column("accel_z", sa.Float(), nullable=True),
        sa.Column("gyro_x", sa.Float(), nullable=True),
        sa.Column("gyro_y", sa.Float(), nullable=True),
        sa.Column("gyro_z", sa.Float(), nullable=True),
        sa.Column("mag_x", sa.Float(), nullable=True),
        sa.Column("mag_y", sa.Float(), nullable=True),
        sa.Column("mag_z", sa.Float(), nullable=True),
        sa.Column("acoustic_level_dbfs", sa.Float(), nullable=True),
        sa.Column("acoustic_category", sa.String(length=24), nullable=True),
        sa.Column("acoustic_confidence", sa.Float(), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_telemetry_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_telemetry_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_telemetry")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_telemetry_dedupe_key")),
        sa.UniqueConstraint("sample_id", name=op.f("uq_telemetry_sample_id")),
    )
    op.create_index(op.f("ix_telemetry_device_id"), "telemetry", ["device_id"], unique=False)
    op.create_index(
        "ix_telemetry_device_received", "telemetry", ["device_id", "received_at"], unique=False
    )
    op.create_index(op.f("ix_telemetry_measured_at"), "telemetry", ["measured_at"], unique=False)
    op.create_index(op.f("ix_telemetry_received_at"), "telemetry", ["received_at"], unique=False)
    op.create_index(op.f("ix_telemetry_simulated"), "telemetry", ["simulated"], unique=False)
    op.create_index(op.f("ix_telemetry_vehicle_id"), "telemetry", ["vehicle_id"], unique=False)
    op.create_index(
        "ix_telemetry_vehicle_received", "telemetry", ["vehicle_id", "received_at"], unique=False
    )
    op.create_table(
        "trips",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_latitude", sa.Float(), nullable=True),
        sa.Column("start_longitude", sa.Float(), nullable=True),
        sa.Column("end_latitude", sa.Float(), nullable=True),
        sa.Column("end_longitude", sa.Float(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("average_speed_kmh", sa.Float(), nullable=True),
        sa.Column("maximum_speed_kmh", sa.Float(), nullable=True),
        sa.Column("speed_sum_kmh", sa.Float(), nullable=False),
        sa.Column("speed_samples", sa.Integer(), nullable=False),
        sa.Column("point_count", sa.Integer(), nullable=False),
        sa.Column("last_latitude", sa.Float(), nullable=True),
        sa.Column("last_longitude", sa.Float(), nullable=True),
        sa.Column("last_point_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_trips_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_trips_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trips")),
    )
    op.create_index("ix_trip_vehicle_start", "trips", ["vehicle_id", "started_at"], unique=False)
    op.create_index(op.f("ix_trips_device_id"), "trips", ["device_id"], unique=False)
    op.create_index(op.f("ix_trips_status"), "trips", ["status"], unique=False)
    op.create_index(op.f("ix_trips_vehicle_id"), "trips", ["vehicle_id"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_key", sa.String(length=255), nullable=False),
        sa.Column("external_event_id", sa.String(length=170), nullable=True),
        sa.Column("vehicle_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("trip_id", sa.Uuid(), nullable=True),
        sa.Column("alert_type", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("simulated", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
            name=op.f("fk_alerts_acknowledged_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_alerts_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_alerts_trip_id_trips"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["vehicle_id"],
            ["vehicles.id"],
            name=op.f("fk_alerts_vehicle_id_vehicles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("event_key", name=op.f("uq_alerts_event_key")),
        sa.UniqueConstraint("external_event_id", name=op.f("uq_alerts_external_event_id")),
    )
    op.create_index(
        "ix_alert_vehicle_status_triggered",
        "alerts",
        ["vehicle_id", "status", "triggered_at"],
        unique=False,
    )
    op.create_index(op.f("ix_alerts_alert_type"), "alerts", ["alert_type"], unique=False)
    op.create_index(op.f("ix_alerts_device_id"), "alerts", ["device_id"], unique=False)
    op.create_index(op.f("ix_alerts_severity"), "alerts", ["severity"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    op.create_index(op.f("ix_alerts_triggered_at"), "alerts", ["triggered_at"], unique=False)
    op.create_index(op.f("ix_alerts_trip_id"), "alerts", ["trip_id"], unique=False)
    op.create_index(op.f("ix_alerts_vehicle_id"), "alerts", ["vehicle_id"], unique=False)
    op.create_table(
        "trip_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trip_id", sa.Uuid(), nullable=False),
        sa.Column("telemetry_id", sa.Integer(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("speed_kmh", sa.Float(), nullable=True),
        sa.Column("hdop", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["telemetry_id"],
            ["telemetry.id"],
            name=op.f("fk_trip_points_telemetry_id_telemetry"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trips.id"], name=op.f("fk_trip_points_trip_id_trips"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trip_points")),
        sa.UniqueConstraint("telemetry_id", name=op.f("uq_trip_points_telemetry_id")),
    )
    op.create_index(
        "ix_trip_point_trip_time", "trip_points", ["trip_id", "recorded_at"], unique=False
    )
    op.create_index(op.f("ix_trip_points_trip_id"), "trip_points", ["trip_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trip_points_trip_id"), table_name="trip_points")
    op.drop_index("ix_trip_point_trip_time", table_name="trip_points")
    op.drop_table("trip_points")
    op.drop_index(op.f("ix_alerts_vehicle_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_trip_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_triggered_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_severity"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_device_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_alert_type"), table_name="alerts")
    op.drop_index("ix_alert_vehicle_status_triggered", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_trips_vehicle_id"), table_name="trips")
    op.drop_index(op.f("ix_trips_status"), table_name="trips")
    op.drop_index(op.f("ix_trips_device_id"), table_name="trips")
    op.drop_index("ix_trip_vehicle_start", table_name="trips")
    op.drop_table("trips")
    op.drop_index("ix_telemetry_vehicle_received", table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_vehicle_id"), table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_simulated"), table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_received_at"), table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_measured_at"), table_name="telemetry")
    op.drop_index("ix_telemetry_device_received", table_name="telemetry")
    op.drop_index(op.f("ix_telemetry_device_id"), table_name="telemetry")
    op.drop_table("telemetry")
    op.drop_index("ix_status_device_changed", table_name="device_status_history")
    op.drop_index(op.f("ix_device_status_history_device_id"), table_name="device_status_history")
    op.drop_table("device_status_history")
    op.drop_index(op.f("ix_commands_state"), table_name="commands")
    op.drop_index(op.f("ix_commands_device_id"), table_name="commands")
    op.drop_index(op.f("ix_commands_command_id"), table_name="commands")
    op.drop_table("commands")
    op.drop_index("ix_acoustic_vehicle_received", table_name="acoustic_measurements")
    op.drop_index(op.f("ix_acoustic_measurements_vehicle_id"), table_name="acoustic_measurements")
    op.drop_index(op.f("ix_acoustic_measurements_device_id"), table_name="acoustic_measurements")
    op.drop_table("acoustic_measurements")
    op.drop_index(op.f("ix_devices_vehicle_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_status"), table_name="devices")
    op.drop_index(op.f("ix_devices_simulated"), table_name="devices")
    op.drop_index(op.f("ix_devices_last_seen_at"), table_name="devices")
    op.drop_index(op.f("ix_devices_device_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_vehicles_vehicle_id"), table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_active"), table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_ingestion_failures_topic"), table_name="ingestion_failures")
    op.drop_index(op.f("ix_ingestion_failures_received_at"), table_name="ingestion_failures")
    op.drop_table("ingestion_failures")
    # ### end Alembic commands ###
